<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "estadistica_unal"
 *
 * Auto generated by Extension Builder 2017-12-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Estadistica Unal',
    'description' => 'Extension diseñada para dar soporte a la exposicion de datos estadisticos para el proyecto de fortalecimiento de la actividad estadistica',
    'category' => 'plugin',
    'author' => 'Alexis Ortiz',
    'author_email' => 'eaortiz@unal.edu.co',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6-8.9',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
